services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - card_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  minio:
    image: minio/minio
    container_name: minio_server
    hostname: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"  # API порт
      - "9001:9001"  # Console порт
    volumes:
      - minio_data:/data
      - ./minio/config:/root/.minio

volumes:
  card_db:
  minio_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./minio/data
